export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';

export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const RESET_CART = 'RESET_CART';

export const INCREASE_NUMBER_OF_PRODUCT = 'INCREASE_NUMBER_OF_PRODUCT'
export const DECREASE_NUMBER_OF_PRODUCT = 'DECREASE_NUMBER_OF_PRODUCT'
export const IS_CHANGE_NUMBER_OF_PRODUCT = 'IS_CHANGE_NUMBER_OF_PRODUCT'
